# Generated by Django 4.2.10 on 2025-11-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fun", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fun",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fun",
            name="fun_fact",
            field=models.TextField(blank=True, null=True),
        ),
    ]
